language: go
go:
  - 1.6

addons:
  hosts:
    - dom1.acmetool-test.devever.net
    - dom2.acmetool-test.devever.net
    - boulder
    - boulder-mysql
    - boulder-rabbitmq
  apt:
    packages:
      - lsb-release
      - gcc
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - rsyslog
      - libcap-dev
      - gcc-multilib
      - libc6-dev-i386
      - libcap-dev:i386
      - debhelper
      - devscripts
      - realpath
      - dput
      - gnupg
      - lintian
      - ncftp
      - rpm
  mariadb: "10.1"

sudo: false

services:
  - rabbitmq

before_install:
  - source ./.travis/before_install
install:
  - go get -v -t ./...
script:
  - source ./.travis/script
after_success:
  - source ./.travis/after_success
before_cache:
  - source ./.travis/before_cache

env:
  global:
    # GITHUB_TOKEN for automatic releases
    - secure: "OA/Trkip03Ee3145oxrbHv3oM7dFpoX2h3y65CzyecQ2v8X4/l5pOwyMiJei5i20zm+QrK0iP9JttbDR9hY71d1DoxMXRGW0YHGFEutUQLZFpkPHLv7klSq8RjRGzpusSaxAtpEF27ZS+7NU42awYynWDzVsK4cglH9CimrS1glr2lKA5bXucqFROlqbI5GzXEdZJXhdGlKZWQWo83Hwe8JTwvIN8xRn5xZ33yxeMDl6SgQ3UhEs6zmsAQphGZ1pNcQaPjtyFtwEBeVQCsYW0loo8gUyjsfippSfGciu+g1J6sGVBj3HxGWWKmMa7lMaCEpL5CUKVcT2WH+LefYLHX5ZkyK8EQwt8QzrO1+X268+SulbWu2rf9SFQlLgoazIa8N8qfd8wVlo6Z3Jiy5YNHhHImMRYtgh5q3lo/5COUrPSgPBx4+VdciuMLxVYw96lTrPcMd4/J2gVYAf7f3AXeOpi/zF0T1WyD/64X0xKquYrbBzGbrEH4EM68vXQBiK5Q2sAEwhMUZNhgAqlKRzpqQoe/Cdx/Stm6cuFt6r87TbJfYiHGCZehveASWwH/Nk1HogOXjv/iVikxOqUiuqy0Q7GLPuFdcAGuLjqxS3wmdN1pBEGVqtSKA/3xrJptKlniz6+1hWr+H1ttTRTgok6ViX/POf+CW11VsfVo7qjyc="
    # PPA_ENCRYPTION_PASS
    - secure: "u9L0PymBiOKz1ylJIaUPzEicW55UZNoXCr8Kd8e0tRG1ABm1GQHC2BUM6AhhHiw33QE8uwe2qf2f5fBupoUsMRnoTh/EZDs8P1Iieg/3vcMZZLI77fQHpc4BcPbVGhHg+3vdR6jg4zRLNW7YLkPAgF9qj7Ezm2b+4MAp+A+9OChWpy1tdck9hftfhJ1ItkFDBufiqTLJEcwME8VgvKVz1zdKaNk3yX7wW4GDvxhuq4ZN6lyfOS6n1VIFWqXKuDWpVemM6ksEAWbdGh/9e9OYd/YxqDTZJT5+MTAUfAy+B00rB2BtR5+zZr9qPgvo5uSLAORrkr2lWRjHBTN1M8s682bry0zViUfMVKfPCGM2UUdGxtc1XQFDUNTi3+iWqQ6jHoeR+CyUxlD4O3F1NU9sHD4Z4mKfUkPfZkD9sy7+i3MojdCQlU9XmTTaxr4J68OwosOIWHUVtG9bNkyq1QhBlXgZOzwJLI47WJQfMoCctu6qG6uFyQ1RRVwZi7R5l5Fj1CvupBsC/BHxegt6+h6sD2gVASxH3oLKP41N8xZSVynd1EJhdPLRoZoGymEAAuplEnUu37BBJfTHxmtA8pu62TNgDjL36F5w+w/HH/lQRpeUUeyA96LSlNc/+gk4b6d5325pd0KlojHjDbU1JE6QYN6T7Xk7sQ0FS6Gxpmy/f4o="
    # COPR_LOGIN_TOKEN
    - secure: "Z6LVNX9CDbfMGusgaYDhtChREfHDx7V+WA2u/M6cPGTqas3SzO2UQFmmNjJFMksjd4foUHEsm6nhGmxrmgbwhFhRSsKNvDtoxu+l6nmeCjUa++/KQlvMdTjo4PIgxCf+kEoEuAnbXb3mtZthIdMNlNBLY9c/cc3+RftxY2IqmmVU9eW0OQNIT3wvYZMtKnI7kdvWdGvCla9LsJ670gh++q41tAj38rLhbhM3ix/goMO/TdrwdhBpXW+AWbSrmYWEbhcfCY/XOqwXjqvlhI/8CmlIIG2hwEDE62/sq9udtYnXc13JAnb6+gw3E1OgvboM1xDvqrbikTaDogbycjwCMRMGeapnHQTwq2m+5p81IMsjErmoIKQ0LOjZU4V/3ATaj+aHcGtBlWhzd/LCpMP44VNdydA1tL8KZCdQFRfEJtPCoriOm4aRl/eUgGXInW0xOfPVyvpLpMw9+JOlctbMZEQOxv89obC6v2JOqJP329q7A1UMVSJ4dsDw1fAy9nM0lbZhj7tVkiT1jMYPKbrZGVgvtSqGHOv2LG/WVtkDKIVF8cOa7vWM87NcJR12LlrBP8JlMf/LUDFYebwmchZIQ/GWjidwaCEOeZvyRfJVrtB62qJt7zEGsEAjQAaSrs761DermkDJ2q0Lq3It6ORJ5ABxC+2hknTnP1Wflak4YRQ="

branches:
  only:
    - master
    - dev
    - /^test-.*$/
    - /^v[0-9].*$/
cache:
  directories:
    - $HOME/tcache

notifications:
  webhooks:
    - https://www.devever.net/.travis-notify
